// Generated by CoffeeScript 1.4.0

/*
* Made by Tomáš Jeřábek, use it as you want.
* https://twitter.com/tjerabek (Say thanks, or follow me, if you want)
*/


(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    SimpleCounter: function(options) {
      var increse, log, settings;
      settings = {
        buttonSelector: '.make-order',
        counterHeight: 0,
        valSelector: '.val',
        move: 0,
        debug: false
      };
      settings = $.extend(settings, options);
      log = function(msg) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
        }
      };
      increse = function() {
        var $newNumber, $numbers, lastNumber;
        $numbers = $('.simple-counter-numbers');
        lastNumber = parseInt($numbers.find('.number').last().text());
        $newNumber = $('<div class="number">' + (lastNumber + 1) + '</div>');
        $numbers.append($newNumber);
        settings.move -= settings.counterHeight;
        $numbers.css('-webkit-transform', 'translate3d(0, ' + settings.move + 'px, 0)');
        $numbers.css('-moz-transform', 'translate3d(0, ' + settings.move + 'px, 0)');
        $numbers.css('-ms-transform', 'translate3d(0, ' + settings.move + 'px, 0)');
        $numbers.css('-o-transform', 'translate3d(0, ' + settings.move + 'px, 0)');
        $numbers.css('transform', 'translate3d(0, ' + settings.move + 'px, 0)');
        if (settings.valSelector !== '') {
          $(settings.valSelector).text(lastNumber + 1);
        }
        return false;
      };
      return this.each(function() {
        var $this;
        $this = $(this);
        $this.wrapInner('<div class="number" />').wrapInner('<div class="simple-counter-numbers numbers" />');
        settings.counterHeight = $this.height();
        log("Item wrapped. Button class: " + settings.buttonSelector + ", Button height: " + settings.counterHeight + ".");
        if (settings.buttonSelector !== '') {
          return $('body').on('click', settings.buttonSelector, increse);
        }
      });
    }
  });

}).call(this);
